### PR TITLE
Fork friendly feature (1/2 on master branch)

### PR DESCRIPTION
**Pull request by redtide**

### CODE REVIEW

**Comment by redtide** [comment]
I forgot about previous changes, if this is OK entirely you need just to skip the third one, otherwise I'll redo this. Sorry for the noise.

**Comment by localnet** [comment]
I have remember it now, I tried this before and it worked to me, but it failed for the forks. I explain you tomorrow.

**Comment by redtide** [comment]
if you are talking about the travis slug change [it works on my fork], I don't see why it shouldn't.

[it works on my fork]: https://github.com/redtide/redtide-aur/blob/master/.travis.yml

**Comment by localnet** [comment]
You are right, excuse me by the noise.

**Comment by redtide** [comment]
no problem, I was wondering if there have been some exception. Thanks for the quick response!

**Pull request merged**
